# Generated by Django 4.1.7 on 2023-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("On Loan", "On Loan"),
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("Lost", "Lost"),
                ],
                default="Available",
                max_length=10,
            ),
        ),
    ]
