version: '3.1'

services:
  postgres_db:
    image: postgres
    container_name: horoscope_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: "-A md5"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
